# Generated by Django 5.0.1 on 2024-01-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('reason_for_request', models.TextField(verbose_name='Motivo de la Solicitud')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado')),
            ],
            options={
                'verbose_name': 'Solicitud de Registro de Usuario',
                'verbose_name_plural': 'Solicitudes de Registro de Usuarios',
            },
        ),
    ]
