# Generated by Django 5.0.1 on 2024-01-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_useraccesslog_delete_userrequest'),
    ]

    operations = [
    ]
